### ISSUE TITLE
issue in using occam

### ISSUE THREAD

**Issue by aatiranum** [SRI-CSL/OCCAM#14]
I want to use occam to specialize programs. I have installed llvm-3.8 version of occam. When I make the hello example, the following error comes

user@admin-vm:~/Documents/OCCAM/examples/hello$ make
slash --work-dir=slash hello.manifest

slash working on hello.bc wrt  ...
Traceback (most recent call last):
  File "/usr/local/bin/slash", line 9, in <module>
    load_entry_point('razor', 'console_scripts', 'slash')()
  File "/home/user/Documents/OCCAM/razor/slash.py", line 62, in entrypoint
    return Slash(sys.argv).run() if utils.checkOccamLib() else 1
  File "/home/user/Documents/OCCAM/razor/slash.py", line 151, in run
    passes.specialize_program_args(pre, post, args, 'arguments', name=name)
  File "/home/user/Documents/OCCAM/razor/passes.py", line 138, in specialize_program_args
    driver.previrt(input_file, output_file, args)
  File "/home/user/Documents/OCCAM/razor/driver.py", line 59, in previrt
    return run(config.get_llvm_tool('opt'), args, **opts)
  File "/home/user/Documents/OCCAM/razor/driver.py", line 92, in run
    stdin=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:28: recipe for target 'slash' failed
make: *** [slash] Error 1

What I have done wrong? Please help.

**Comment by ianamason** [comment]
Looks like the hello Makefile needs some TLC.

It is complaining that the slash subdirectory of the hello example does not exist,
which is reasonable, since no one seems to have made it. 

I will see if I can spruce it up a bit in the next day or so. In the meantime try:

```
mkdir slash
make
```
